name: Manual Dagger Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  dagger:
    name : Run Dagger pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.4'

      - name: Install Go dependencies
        run: |
          if [ -f go.mod ]; then
            go mod download
          fi

      - name: Run Dagger pipeline
        uses: dagger/dagger-for-github@v8.2.0
        with:
          verb: run
          args: go run pipeline.go
          version: "0.19.7"

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: model
          path: output/lead_model_lr.pkl
      
      # renaming path and model for the validator 
      - name: Download artifact for renaming
        uses: actions/download-artifact@v4
        with:
          name: model
          path: model-temp
          
      - name: Prepare model for validator
        run: |
          mkdir -p model
          mv model-temp/lead_model_lr.pkl model/model.pkl
          rm -rf model-temp
          
      - name: Re-upload with correct name
        uses: actions/upload-artifact@v4.4.0
        with:
          name: model
          path: model/model.pkl
          overwrite: true

      - name: Run Model Inference Test Action
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
