name: Manual Dagger Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  dagger:
    name : Run Dagger pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.4'

      - name: Install Dagger CLI
        run: |
          curl -fL https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.19.7 sh
          ls -la "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify Dagger install
        run: dagger version

      # Running locally instead of using the action because 
      # it was throwing an error on the GitHub side
      - name: Run Dagger pipeline
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          dagger version
          dagger run go run pipeline.go

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: model
          path: output/lead_model_lr.pkl

      - name: Run Model Inference Test Action
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
